<?php

function leaflet_custom_map_preprocess_page(&$vars, $hook) {
  if (true) {
    drupal_add_js([
      'leaflet_custom_map' => [
        'url' => 'https://cdn-images-1.medium.com/max/2000/1*tSyuv3ZRCfsSD5aXB7v8DQ.png',
        'bounds' => '[[53.0, -5.0], [40.58, 19.17]]'
      ]
    ], 'setting');

    drupal_add_js(drupal_get_path('module', 'leaflet_custom_map') . '/leaflet_custom_map.js');
  }
}